repos:
  - repo: local
    hooks:
      - id: absolufy-imports
        name: absolufy-imports
        stages: [ commit ]
        language: system
        entry: poetry run absolufy-imports
        types: [ python ]
        exclude: alembic
      - id: ruff_check
        name: ruff-check
        stages: [ commit ]
        language: system
        entry: poetry run ruff check
        types: [ python ]
        exclude: alembic
      - id: ruff_format
        name: ruff-format
        stages: [ commit ]
        language: system
        entry: poetry run ruff format
        types: [ python ]
        exclude: alembic
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy
        args: [--disallow-untyped-defs, --disallow-incomplete-defs, --no-implicit-optional, --local-partial-types, --strict-equality, ]
        types: [python]
        require_serial: true
        exclude: alembic
      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: poetry run pylint
        types: [python]
        exclude: alembic
      - id: bandit
        name: bandit
        stages: [commit]
        language: system
        entry: poetry run bandit
        args: ['-c', 'pyproject.toml', '-r', 'packagebusters']
        types: [python]
        exclude: alembic
